/**
 * (PECL haru >= 0.0.1)<br/>
 * @link http://php.net/manual/en/harupage.getgmode.php
 * @return int 現在のグラフィックスモードを返します。
 * 結果は次のいずれかの値となります。HaruPage::GMODE_PAGE_DESCRIPTION
 * HaruPage::GMODE_TEXT_OBJECT
 * HaruPage::GMODE_PATH_OBJECT
 * HaruPage::GMODE_CLIPPING_PATH
 * HaruPage::GMODE_SHADING
 * HaruPage::GMODE_INLINE_IMAGE
 * HaruPage::GMODE_EXTERNAL_OBJECTHaruPage::GMODE_PAGE_DESCRIPTION
 * HaruPage::GMODE_TEXT_OBJECT
 * HaruPage::GMODE_PATH_OBJECT
 * HaruPage::GMODE_CLIPPING_PATH
 * HaruPage::GMODE_SHADING
 * HaruPage::GMODE_INLINE_IMAGE
 * HaruPage::GMODE_EXTERNAL_OBJECTHaruPage::GMODE_PAGE_DESCRIPTIONHaruPage::GMODE_PAGE_DESCRIPTIONHaruPage::GMODE_TEXT_OBJECTHaruPage::GMODE_TEXT_OBJECTHaruPage::GMODE_PATH_OBJECTHaruPage::GMODE_PATH_OBJECTHaruPage::GMODE_CLIPPING_PATHHaruPage::GMODE_CLIPPING_PATHHaruPage::GMODE_SHADINGHaruPage::GMODE_SHADINGHaruPage::GMODE_INLINE_IMAGEHaruPage::GMODE_INLINE_IMAGEHaruPage::GMODE_EXTERNAL_OBJECTHaruPage::GMODE_EXTERNAL_OBJECT
 */
function HaruPage.getGMode() {}