/**
 * (PECL imagick 0.9.10-0.9.9)<br/>
 * @link http://php.net/manual/en/imagick.getimagetype.php
 * @return int 画像の型を返します。
 * imagick::IMGTYPE_UNDEFINED
 * imagick::IMGTYPE_BILEVEL
 * imagick::IMGTYPE_GRAYSCALE
 * imagick::IMGTYPE_GRAYSCALEMATTE
 * imagick::IMGTYPE_PALETTE
 * imagick::IMGTYPE_PALETTEMATTE
 * imagick::IMGTYPE_TRUECOLOR
 * imagick::IMGTYPE_TRUECOLORMATTE
 * imagick::IMGTYPE_COLORSEPARATION
 * imagick::IMGTYPE_COLORSEPARATIONMATTE
 * imagick::IMGTYPE_OPTIMIZEimagick::IMGTYPE_UNDEFINED
 * imagick::IMGTYPE_BILEVEL
 * imagick::IMGTYPE_GRAYSCALE
 * imagick::IMGTYPE_GRAYSCALEMATTE
 * imagick::IMGTYPE_PALETTE
 * imagick::IMGTYPE_PALETTEMATTE
 * imagick::IMGTYPE_TRUECOLOR
 * imagick::IMGTYPE_TRUECOLORMATTE
 * imagick::IMGTYPE_COLORSEPARATION
 * imagick::IMGTYPE_COLORSEPARATIONMATTE
 * imagick::IMGTYPE_OPTIMIZEimagick::IMGTYPE_UNDEFINEDimagick::IMGTYPE_UNDEFINEDimagick::IMGTYPE_UNDEFINEDimagick::IMGTYPE_BILEVELimagick::IMGTYPE_BILEVELimagick::IMGTYPE_BILEVELimagick::IMGTYPE_GRAYSCALEimagick::IMGTYPE_GRAYSCALEimagick::IMGTYPE_GRAYSCALEimagick::IMGTYPE_GRAYSCALEMATTEimagick::IMGTYPE_GRAYSCALEMATTEimagick::IMGTYPE_GRAYSCALEMATTEimagick::IMGTYPE_PALETTEimagick::IMGTYPE_PALETTEimagick::IMGTYPE_PALETTEimagick::IMGTYPE_PALETTEMATTEimagick::IMGTYPE_PALETTEMATTEimagick::IMGTYPE_PALETTEMATTEimagick::IMGTYPE_TRUECOLORimagick::IMGTYPE_TRUECOLORimagick::IMGTYPE_TRUECOLORimagick::IMGTYPE_TRUECOLORMATTEimagick::IMGTYPE_TRUECOLORMATTEimagick::IMGTYPE_TRUECOLORMATTEimagick::IMGTYPE_COLORSEPARATIONimagick::IMGTYPE_COLORSEPARATIONimagick::IMGTYPE_COLORSEPARATIONimagick::IMGTYPE_COLORSEPARATIONMATTEimagick::IMGTYPE_COLORSEPARATIONMATTEimagick::IMGTYPE_COLORSEPARATIONMATTEimagick::IMGTYPE_OPTIMIZEimagick::IMGTYPE_OPTIMIZEimagick::IMGTYPE_OPTIMIZE
 */
function Imagick.getImageType() {}