/**
 * (PHP 7)<br/>
 * @link http://php.net/manual/en/intlchar.chartype.php
 * @param mixed $codepoint [optional] <p> TODO DESCRIPTION </p>
 * @return int Returns the general category type, which may be one of the following constants:
 * IntlChar::CHAR_CATEGORY_UNASSIGNED
 * IntlChar::CHAR_CATEGORY_GENERAL_OTHER_TYPES
 * IntlChar::CHAR_CATEGORY_UPPERCASE_LETTER
 * IntlChar::CHAR_CATEGORY_LOWERCASE_LETTER
 * IntlChar::CHAR_CATEGORY_TITLECASE_LETTER
 * IntlChar::CHAR_CATEGORY_MODIFIER_LETTER
 * IntlChar::CHAR_CATEGORY_OTHER_LETTER
 * IntlChar::CHAR_CATEGORY_NON_SPACING_MARK
 * IntlChar::CHAR_CATEGORY_ENCLOSING_MARK
 * IntlChar::CHAR_CATEGORY_COMBINING_SPACING_MARK
 * IntlChar::CHAR_CATEGORY_DECIMAL_DIGIT_NUMBER
 * IntlChar::CHAR_CATEGORY_LETTER_NUMBER
 * IntlChar::CHAR_CATEGORY_OTHER_NUMBER
 * IntlChar::CHAR_CATEGORY_SPACE_SEPARATOR
 * IntlChar::CHAR_CATEGORY_LINE_SEPARATOR
 * IntlChar::CHAR_CATEGORY_PARAGRAPH_SEPARATOR
 * IntlChar::CHAR_CATEGORY_CONTROL_CHAR
 * IntlChar::CHAR_CATEGORY_FORMAT_CHAR
 * IntlChar::CHAR_CATEGORY_PRIVATE_USE_CHAR
 * IntlChar::CHAR_CATEGORY_SURROGATE
 * IntlChar::CHAR_CATEGORY_DASH_PUNCTUATION
 * IntlChar::CHAR_CATEGORY_START_PUNCTUATION
 * IntlChar::CHAR_CATEGORY_END_PUNCTUATION
 * IntlChar::CHAR_CATEGORY_CONNECTOR_PUNCTUATION
 * IntlChar::CHAR_CATEGORY_OTHER_PUNCTUATION
 * IntlChar::CHAR_CATEGORY_MATH_SYMBOL
 * IntlChar::CHAR_CATEGORY_CURRENCY_SYMBOL
 * IntlChar::CHAR_CATEGORY_MODIFIER_SYMBOL
 * IntlChar::CHAR_CATEGORY_OTHER_SYMBOL
 * IntlChar::CHAR_CATEGORY_INITIAL_PUNCTUATION
 * IntlChar::CHAR_CATEGORY_FINAL_PUNCTUATION
 * IntlChar::CHAR_CATEGORY_CHAR_CATEGORY_COUNTIntlChar::CHAR_CATEGORY_UNASSIGNED
 * IntlChar::CHAR_CATEGORY_GENERAL_OTHER_TYPES
 * IntlChar::CHAR_CATEGORY_UPPERCASE_LETTER
 * IntlChar::CHAR_CATEGORY_LOWERCASE_LETTER
 * IntlChar::CHAR_CATEGORY_TITLECASE_LETTER
 * IntlChar::CHAR_CATEGORY_MODIFIER_LETTER
 * IntlChar::CHAR_CATEGORY_OTHER_LETTER
 * IntlChar::CHAR_CATEGORY_NON_SPACING_MARK
 * IntlChar::CHAR_CATEGORY_ENCLOSING_MARK
 * IntlChar::CHAR_CATEGORY_COMBINING_SPACING_MARK
 * IntlChar::CHAR_CATEGORY_DECIMAL_DIGIT_NUMBER
 * IntlChar::CHAR_CATEGORY_LETTER_NUMBER
 * IntlChar::CHAR_CATEGORY_OTHER_NUMBER
 * IntlChar::CHAR_CATEGORY_SPACE_SEPARATOR
 * IntlChar::CHAR_CATEGORY_LINE_SEPARATOR
 * IntlChar::CHAR_CATEGORY_PARAGRAPH_SEPARATOR
 * IntlChar::CHAR_CATEGORY_CONTROL_CHAR
 * IntlChar::CHAR_CATEGORY_FORMAT_CHAR
 * IntlChar::CHAR_CATEGORY_PRIVATE_USE_CHAR
 * IntlChar::CHAR_CATEGORY_SURROGATE
 * IntlChar::CHAR_CATEGORY_DASH_PUNCTUATION
 * IntlChar::CHAR_CATEGORY_START_PUNCTUATION
 * IntlChar::CHAR_CATEGORY_END_PUNCTUATION
 * IntlChar::CHAR_CATEGORY_CONNECTOR_PUNCTUATION
 * IntlChar::CHAR_CATEGORY_OTHER_PUNCTUATION
 * IntlChar::CHAR_CATEGORY_MATH_SYMBOL
 * IntlChar::CHAR_CATEGORY_CURRENCY_SYMBOL
 * IntlChar::CHAR_CATEGORY_MODIFIER_SYMBOL
 * IntlChar::CHAR_CATEGORY_OTHER_SYMBOL
 * IntlChar::CHAR_CATEGORY_INITIAL_PUNCTUATION
 * IntlChar::CHAR_CATEGORY_FINAL_PUNCTUATION
 * IntlChar::CHAR_CATEGORY_CHAR_CATEGORY_COUNTIntlChar::CHAR_CATEGORY_UNASSIGNEDIntlChar::CHAR_CATEGORY_UNASSIGNEDIntlChar::CHAR_CATEGORY_GENERAL_OTHER_TYPESIntlChar::CHAR_CATEGORY_GENERAL_OTHER_TYPESIntlChar::CHAR_CATEGORY_UPPERCASE_LETTERIntlChar::CHAR_CATEGORY_UPPERCASE_LETTERIntlChar::CHAR_CATEGORY_LOWERCASE_LETTERIntlChar::CHAR_CATEGORY_LOWERCASE_LETTERIntlChar::CHAR_CATEGORY_TITLECASE_LETTERIntlChar::CHAR_CATEGORY_TITLECASE_LETTERIntlChar::CHAR_CATEGORY_MODIFIER_LETTERIntlChar::CHAR_CATEGORY_MODIFIER_LETTERIntlChar::CHAR_CATEGORY_OTHER_LETTERIntlChar::CHAR_CATEGORY_OTHER_LETTERIntlChar::CHAR_CATEGORY_NON_SPACING_MARKIntlChar::CHAR_CATEGORY_NON_SPACING_MARKIntlChar::CHAR_CATEGORY_ENCLOSING_MARKIntlChar::CHAR_CATEGORY_ENCLOSING_MARKIntlChar::CHAR_CATEGORY_COMBINING_SPACING_MARKIntlChar::CHAR_CATEGORY_COMBINING_SPACING_MARKIntlChar::CHAR_CATEGORY_DECIMAL_DIGIT_NUMBERIntlChar::CHAR_CATEGORY_DECIMAL_DIGIT_NUMBERIntlChar::CHAR_CATEGORY_LETTER_NUMBERIntlChar::CHAR_CATEGORY_LETTER_NUMBERIntlChar::CHAR_CATEGORY_OTHER_NUMBERIntlChar::CHAR_CATEGORY_OTHER_NUMBERIntlChar::CHAR_CATEGORY_SPACE_SEPARATORIntlChar::CHAR_CATEGORY_SPACE_SEPARATORIntlChar::CHAR_CATEGORY_LINE_SEPARATORIntlChar::CHAR_CATEGORY_LINE_SEPARATORIntlChar::CHAR_CATEGORY_PARAGRAPH_SEPARATORIntlChar::CHAR_CATEGORY_PARAGRAPH_SEPARATORIntlChar::CHAR_CATEGORY_CONTROL_CHARIntlChar::CHAR_CATEGORY_CONTROL_CHARIntlChar::CHAR_CATEGORY_FORMAT_CHARIntlChar::CHAR_CATEGORY_FORMAT_CHARIntlChar::CHAR_CATEGORY_PRIVATE_USE_CHARIntlChar::CHAR_CATEGORY_PRIVATE_USE_CHARIntlChar::CHAR_CATEGORY_SURROGATEIntlChar::CHAR_CATEGORY_SURROGATEIntlChar::CHAR_CATEGORY_DASH_PUNCTUATIONIntlChar::CHAR_CATEGORY_DASH_PUNCTUATIONIntlChar::CHAR_CATEGORY_START_PUNCTUATIONIntlChar::CHAR_CATEGORY_START_PUNCTUATIONIntlChar::CHAR_CATEGORY_END_PUNCTUATIONIntlChar::CHAR_CATEGORY_END_PUNCTUATIONIntlChar::CHAR_CATEGORY_CONNECTOR_PUNCTUATIONIntlChar::CHAR_CATEGORY_CONNECTOR_PUNCTUATIONIntlChar::CHAR_CATEGORY_OTHER_PUNCTUATIONIntlChar::CHAR_CATEGORY_OTHER_PUNCTUATIONIntlChar::CHAR_CATEGORY_MATH_SYMBOLIntlChar::CHAR_CATEGORY_MATH_SYMBOLIntlChar::CHAR_CATEGORY_CURRENCY_SYMBOLIntlChar::CHAR_CATEGORY_CURRENCY_SYMBOLIntlChar::CHAR_CATEGORY_MODIFIER_SYMBOLIntlChar::CHAR_CATEGORY_MODIFIER_SYMBOLIntlChar::CHAR_CATEGORY_OTHER_SYMBOLIntlChar::CHAR_CATEGORY_OTHER_SYMBOLIntlChar::CHAR_CATEGORY_INITIAL_PUNCTUATIONIntlChar::CHAR_CATEGORY_INITIAL_PUNCTUATIONIntlChar::CHAR_CATEGORY_FINAL_PUNCTUATIONIntlChar::CHAR_CATEGORY_FINAL_PUNCTUATIONIntlChar::CHAR_CATEGORY_CHAR_CATEGORY_COUNTIntlChar::CHAR_CATEGORY_CHAR_CATEGORY_COUNT
 */
function IntlChar.charType($codepoint) {}