/**
 * (PHP 4, PHP 5, PHP 7)<br/>
 * @link http://php.net/manual/en/function.odbc-gettypeinfo.php
 * @param resource $connection_id [optional] <p> TODO DESCRIPTION </p>
 * @param int $data_type [optional] <p> TODO DESCRIPTION </p>
 * @return resource ODBC 結果 ID または失敗した場合に FALSE を返します。FALSE結果は、以下のようなカラムを持つものとなります。
 * TYPE_NAME
 * DATA_TYPE
 * PRECISION
 * LITERAL_PREFIX
 * LITERAL_SUFFIX
 * CREATE_PARAMS
 * NULLABLE
 * CASE_SENSITIVE
 * SEARCHABLE
 * UNSIGNED_ATTRIBUTE
 * MONEY
 * AUTO_INCREMENT
 * LOCAL_TYPE_NAME
 * MINIMUM_SCALE
 * MAXIMUM_SCALETYPE_NAME
 * DATA_TYPE
 * PRECISION
 * LITERAL_PREFIX
 * LITERAL_SUFFIX
 * CREATE_PARAMS
 * NULLABLE
 * CASE_SENSITIVE
 * SEARCHABLE
 * UNSIGNED_ATTRIBUTE
 * MONEY
 * AUTO_INCREMENT
 * LOCAL_TYPE_NAME
 * MINIMUM_SCALE
 * MAXIMUM_SCALETYPE_NAMETYPE_NAMEDATA_TYPEDATA_TYPEPRECISIONPRECISIONLITERAL_PREFIXLITERAL_PREFIXLITERAL_SUFFIXLITERAL_SUFFIXCREATE_PARAMSCREATE_PARAMSNULLABLENULLABLECASE_SENSITIVECASE_SENSITIVESEARCHABLESEARCHABLEUNSIGNED_ATTRIBUTEUNSIGNED_ATTRIBUTEMONEYMONEYAUTO_INCREMENTAUTO_INCREMENTLOCAL_TYPE_NAMELOCAL_TYPE_NAMEMINIMUM_SCALEMINIMUM_SCALEMAXIMUM_SCALEMAXIMUM_SCALE結果セットは、DATA_TYPE および TYPE_NAME でソートされます。
 */
function odbc_gettypeinfo($connection_id, $data_type) {}