/**
 * (PHP 5, PHP 7)<br/>
 * @link http://php.net/manual/en/function.variant-imp.php
 * @param mixed $left [optional] <p> TODO DESCRIPTION </p>
 * @param mixed $right [optional] <p> TODO DESCRIPTION </p>
 * @return mixed Variant Implication テーブル
 * left
 * right
 * 結果
 * TRUETRUETRUE
 * TRUEFALSETRUE
 * TRUENULLTRUE
 * FALSETRUETRUE
 * FALSEFALSETRUE
 * FALSENULLTRUE
 * NULLTRUETRUE
 * NULLFALSENULL
 * NULLNULLNULLVariant Implication テーブル
 * left
 * right
 * 結果
 * TRUETRUETRUE
 * TRUEFALSETRUE
 * TRUENULLTRUE
 * FALSETRUETRUE
 * FALSEFALSETRUE
 * FALSENULLTRUE
 * NULLTRUETRUE
 * NULLFALSENULL
 * NULLNULLNULLleft
 * right
 * 結果
 * TRUETRUETRUE
 * TRUEFALSETRUE
 * TRUENULLTRUE
 * FALSETRUETRUE
 * FALSEFALSETRUE
 * FALSENULLTRUE
 * NULLTRUETRUE
 * NULLFALSENULL
 * NULLNULLNULLleft
 * right
 * 結果left
 * right
 * 結果leftleftrightright結果TRUETRUETRUE
 * TRUEFALSETRUE
 * TRUENULLTRUE
 * FALSETRUETRUE
 * FALSEFALSETRUE
 * FALSENULLTRUE
 * NULLTRUETRUE
 * NULLFALSENULL
 * NULLNULLNULLTRUETRUETRUETRUETRUETRUETRUETRUETRUETRUEFALSETRUETRUETRUEFALSEFALSETRUETRUETRUENULLTRUETRUETRUENULLNULLTRUETRUEFALSETRUETRUEFALSEFALSETRUETRUETRUETRUEFALSEFALSETRUEFALSEFALSEFALSEFALSETRUETRUEFALSENULLTRUEFALSEFALSENULLNULLTRUETRUENULLTRUETRUENULLNULLTRUETRUETRUETRUENULLFALSENULLNULLNULLFALSEFALSENULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULL
 */
function variant_imp($left, $right) {}