/**
 * (PHP 5, PHP 7)<br/>
 * @link http://php.net/manual/en/function.variant-and.php
 * @param mixed $left [optional] <p> TODO DESCRIPTION </p>
 * @param mixed $right [optional] <p> TODO DESCRIPTION </p>
 * @return mixed Variant の AND 規則
 * left
 * right
 * 結果
 * TRUETRUETRUE
 * TRUEFALSEFALSE
 * TRUENULLNULL
 * FALSETRUEFALSE
 * FALSEFALSEFALSE
 * FALSENULLFALSE
 * NULLTRUENULL
 * NULLFALSEFALSE
 * NULLNULLNULLVariant の AND 規則
 * left
 * right
 * 結果
 * TRUETRUETRUE
 * TRUEFALSEFALSE
 * TRUENULLNULL
 * FALSETRUEFALSE
 * FALSEFALSEFALSE
 * FALSENULLFALSE
 * NULLTRUENULL
 * NULLFALSEFALSE
 * NULLNULLNULLleft
 * right
 * 結果
 * TRUETRUETRUE
 * TRUEFALSEFALSE
 * TRUENULLNULL
 * FALSETRUEFALSE
 * FALSEFALSEFALSE
 * FALSENULLFALSE
 * NULLTRUENULL
 * NULLFALSEFALSE
 * NULLNULLNULLleft
 * right
 * 結果left
 * right
 * 結果leftleftrightright結果TRUETRUETRUE
 * TRUEFALSEFALSE
 * TRUENULLNULL
 * FALSETRUEFALSE
 * FALSEFALSEFALSE
 * FALSENULLFALSE
 * NULLTRUENULL
 * NULLFALSEFALSE
 * NULLNULLNULLTRUETRUETRUETRUETRUETRUETRUETRUETRUETRUEFALSEFALSETRUETRUEFALSEFALSEFALSEFALSETRUENULLNULLTRUETRUENULLNULLNULLNULLFALSETRUEFALSEFALSEFALSETRUETRUEFALSEFALSEFALSEFALSEFALSEFALSEFALSEFALSEFALSEFALSEFALSEFALSENULLFALSEFALSEFALSENULLNULLFALSEFALSENULLTRUENULLNULLNULLTRUETRUENULLNULLNULLFALSEFALSENULLNULLFALSEFALSEFALSEFALSENULLNULLNULLNULLNULLNULLNULLNULLNULL
 */
function variant_and($left, $right) {}