/**
 * (PHP 5, PHP 7)<br/>
 * @link http://php.net/manual/en/function.variant-or.php
 * @param mixed $left [optional] <p> TODO DESCRIPTION </p>
 * @param mixed $right [optional] <p> TODO DESCRIPTION </p>
 * @return mixed Variant の OR 規則
 * left
 * right
 * 結果
 * TRUETRUETRUE
 * TRUEFALSETRUE
 * TRUENULLTRUE
 * FALSETRUETRUE
 * FALSEFALSEFALSE
 * FALSENULLNULL
 * NULLTRUETRUE
 * NULLFALSENULL
 * NULLNULLNULLVariant の OR 規則
 * left
 * right
 * 結果
 * TRUETRUETRUE
 * TRUEFALSETRUE
 * TRUENULLTRUE
 * FALSETRUETRUE
 * FALSEFALSEFALSE
 * FALSENULLNULL
 * NULLTRUETRUE
 * NULLFALSENULL
 * NULLNULLNULLleft
 * right
 * 結果
 * TRUETRUETRUE
 * TRUEFALSETRUE
 * TRUENULLTRUE
 * FALSETRUETRUE
 * FALSEFALSEFALSE
 * FALSENULLNULL
 * NULLTRUETRUE
 * NULLFALSENULL
 * NULLNULLNULLleft
 * right
 * 結果left
 * right
 * 結果leftleftrightright結果TRUETRUETRUE
 * TRUEFALSETRUE
 * TRUENULLTRUE
 * FALSETRUETRUE
 * FALSEFALSEFALSE
 * FALSENULLNULL
 * NULLTRUETRUE
 * NULLFALSENULL
 * NULLNULLNULLTRUETRUETRUETRUETRUETRUETRUETRUETRUETRUEFALSETRUETRUETRUEFALSEFALSETRUETRUETRUENULLTRUETRUETRUENULLNULLTRUETRUEFALSETRUETRUEFALSEFALSETRUETRUETRUETRUEFALSEFALSEFALSEFALSEFALSEFALSEFALSEFALSEFALSEFALSENULLNULLFALSEFALSENULLNULLNULLNULLNULLTRUETRUENULLNULLTRUETRUETRUETRUENULLFALSENULLNULLNULLFALSEFALSENULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULL
 */
function variant_or($left, $right) {}