/**
 * (PHP 5, PHP 7)<br/>
 * @link http://php.net/manual/en/function.variant-xor.php
 * @param mixed $left [optional] <p> TODO DESCRIPTION </p>
 * @param mixed $right [optional] <p> TODO DESCRIPTION </p>
 * @return mixed Variant の XOR 規則
 * left
 * right
 * 結果
 * TRUETRUEFALSE
 * TRUEFALSETRUE
 * FALSETRUETRUE
 * FALSEFALSEFALSE
 * NULLNULLNULLVariant の XOR 規則
 * left
 * right
 * 結果
 * TRUETRUEFALSE
 * TRUEFALSETRUE
 * FALSETRUETRUE
 * FALSEFALSEFALSE
 * NULLNULLNULLleft
 * right
 * 結果
 * TRUETRUEFALSE
 * TRUEFALSETRUE
 * FALSETRUETRUE
 * FALSEFALSEFALSE
 * NULLNULLNULLleft
 * right
 * 結果left
 * right
 * 結果leftleftrightright結果TRUETRUEFALSE
 * TRUEFALSETRUE
 * FALSETRUETRUE
 * FALSEFALSEFALSE
 * NULLNULLNULLTRUETRUEFALSETRUETRUETRUETRUEFALSEFALSETRUEFALSETRUETRUETRUEFALSEFALSETRUETRUEFALSETRUETRUEFALSEFALSETRUETRUETRUETRUEFALSEFALSEFALSEFALSEFALSEFALSEFALSEFALSEFALSENULLNULLNULLNULLNULLNULLNULLNULLNULL
 */
function variant_xor($left, $right) {}