/**
 * (PECL win32service SVN)<br/>
 * @link http://php.net/manual/en/function.win32-get-last-control-message.php
 * @return int 制御コード定数を返します。以下の
 * Win32Service サービス制御メッセージ定数
 * のひとつです。
 * WIN32_SERVICE_CONTROL_CONTINUE、
 * WIN32_SERVICE_CONTROL_INTERROGATE、
 * WIN32_SERVICE_CONTROL_PAUSE、
 * WIN32_SERVICE_CONTROL_PRESHUTDOWN、
 * WIN32_SERVICE_CONTROL_SHUTDOWN、
 * WIN32_SERVICE_CONTROL_STOP。Win32Service サービス制御メッセージ定数WIN32_SERVICE_CONTROL_CONTINUEWIN32_SERVICE_CONTROL_INTERROGATEWIN32_SERVICE_CONTROL_PAUSEWIN32_SERVICE_CONTROL_PRESHUTDOWNWIN32_SERVICE_CONTROL_SHUTDOWNWIN32_SERVICE_CONTROL_STOP
 */
function win32_get_last_control_message() {}