/**
 * (PHP >= 5.4.0)<br/>
 * @link http://php.net/manual/en/xsltprocessor.getsecurityprefs.php
 * @return int XSL_SECPREF_READ_FILE、
 * XSL_SECPREF_WRITE_FILE、
 * XSL_SECPREF_CREATE_DIRECTORY、
 * XSL_SECPREF_READ_NETWORK、
 * XSL_SECPREF_WRITE_NETWORK を含むビットマスクを返します。XSL_SECPREF_READ_FILEXSL_SECPREF_WRITE_FILEXSL_SECPREF_CREATE_DIRECTORYXSL_SECPREF_READ_NETWORKXSL_SECPREF_WRITE_NETWORK
 */
function XsltProcessor.getSecurityPrefs() {}